#!/usr/bin/perl -w -- 
#
# generated by wxGlade 1.1.1 on Wed Feb 12 23:56:02 2025
#
# To get wxPerl visit http://www.wxperl.it
#

use Wx;
use strict;

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package MyFrame;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
    my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $title  = ""                 unless defined $title;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: MyFrame::new
    $style = wxDEFAULT_FRAME_STYLE
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
    $self->SetSize(Wx::Size->new(765, 752));
    $self->SetTitle("ADCIRC.live GUIde (C)");
    
    $self->{panel_1} = Wx::Panel->new($self, wxID_ANY);
    
    $self->{sizer_1} = Wx::BoxSizer->new(wxVERTICAL);
    
    $self->{notebook_1} = Wx::Notebook->new($self->{panel_1}, wxID_ANY);
    $self->{sizer_1}->Add($self->{notebook_1}, 1, wxEXPAND, 0);
    
    $self->{notebook_1_ASGSUtilities} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_ASGSUtilities}, "ASGS Tools");
    
    $self->{notebook_1_pane_1} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_pane_1}, "Output Viz Helpers");
    
    $self->{sizer_2} = Wx::BoxSizer->new(wxHORIZONTAL);
    
    $self->{notebook_2} = Wx::Notebook->new($self->{notebook_1_pane_1}, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_LEFT);
    $self->{notebook_2}->SetFont(Wx::Font->new(9, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD, 0, ""));
    $self->{sizer_2}->Add($self->{notebook_2}, 1, wxEXPAND, 0);
    
    $self->{notebook_2_pane_1} = Wx::Panel->new($self->{notebook_2}, wxID_ANY);
    $self->{notebook_2}->AddPage($self->{notebook_2_pane_1}, "XDMF Static");
    
    $self->{sizer_3} = Wx::FlexGridSizer->new(1, 2, 0, 0);
    
    $self->{sizer_5} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_3}->Add($self->{sizer_5}, 1, wxEXPAND, 0);
    
    $self->{sizer_6} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->{sizer_5}->Add($self->{sizer_6}, 1, wxEXPAND, 0);
    
    $self->{grid_sizer_1} = Wx::GridSizer->new(8, 4, 0, 0);
    $self->{sizer_6}->Add($self->{grid_sizer_1}, 1, wxEXPAND, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    my $label_3 = Wx::StaticText->new($self->{notebook_2_pane_1}, wxID_ANY, "Grid");
    $label_3->SetFont(Wx::Font->new(9, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD, 0, ""));
    $self->{grid_sizer_1}->Add($label_3, 0, wxALIGN_RIGHT, 0);
    
    $self->{combo_box_1} = Wx::ComboBox->new($self->{notebook_2_pane_1}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, ["Choose ..."], wxCB_DROPDOWN);
    $self->{combo_box_1}->SetSelection(0);
    $self->{grid_sizer_1}->Add($self->{combo_box_1}, 0, 0, 0);
    
    $self->{button_2} = Wx::Button->new($self->{notebook_2_pane_1}, wxID_ANY, "Download ...");
    $self->{grid_sizer_1}->Add($self->{button_2}, 0, 0, 0);
    
    $self->{button_5} = Wx::Button->new($self->{notebook_2_pane_1}, wxID_ANY, "Browse ...");
    $self->{grid_sizer_1}->Add($self->{button_5}, 0, wxALIGN_RIGHT, 0);
    
    my $label_4 = Wx::StaticText->new($self->{notebook_2_pane_1}, wxID_ANY, "Outputs");
    $label_4->SetFont(Wx::Font->new(9, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD, 0, ""));
    $self->{grid_sizer_1}->Add($label_4, 0, wxALIGN_RIGHT, 0);
    
    $self->{checkbox_1} = Wx::CheckBox->new($self->{notebook_2_pane_1}, wxID_ANY, "maxele.63.nc");
    $self->{grid_sizer_1}->Add($self->{checkbox_1}, 0, 0, 0);
    
    $self->{checkbox_2} = Wx::CheckBox->new($self->{notebook_2_pane_1}, wxID_ANY, "maxrs.63.nc");
    $self->{grid_sizer_1}->Add($self->{checkbox_2}, 0, 0, 0);
    
    $self->{checkbox_3} = Wx::CheckBox->new($self->{notebook_2_pane_1}, wxID_ANY, "maxwvel.63.nc");
    $self->{grid_sizer_1}->Add($self->{checkbox_3}, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{checkbox_5} = Wx::CheckBox->new($self->{notebook_2_pane_1}, wxID_ANY, "maxvel.63.nc");
    $self->{grid_sizer_1}->Add($self->{checkbox_5}, 0, 0, 0);
    
    $self->{checkbox_7} = Wx::CheckBox->new($self->{notebook_2_pane_1}, wxID_ANY, "minpr.63.nc");
    $self->{grid_sizer_1}->Add($self->{checkbox_7}, 0, 0, 0);
    
    $self->{checkbox_4} = Wx::CheckBox->new($self->{notebook_2_pane_1}, wxID_ANY, "swan_HS");
    $self->{grid_sizer_1}->Add($self->{checkbox_4}, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{checkbox_6} = Wx::CheckBox->new($self->{notebook_2_pane_1}, wxID_ANY, "swan_TPS");
    $self->{grid_sizer_1}->Add($self->{checkbox_6}, 0, 0, 0);
    
    my $label_5 = Wx::StaticText->new($self->{notebook_2_pane_1}, wxID_ANY, "Software Details");
    $label_5->SetFont(Wx::Font->new(9, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD, 0, ""));
    $self->{grid_sizer_1}->Add($label_5, 0, wxALIGN_RIGHT, 0);
    
    my $label_1 = Wx::StaticText->new($self->{notebook_2_pane_1}, wxID_ANY, "Paraview");
    $self->{grid_sizer_1}->Add($label_1, 0, wxALIGN_RIGHT, 0);
    
    $self->{combo_box_2} = Wx::ComboBox->new($self->{notebook_2_pane_1}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, ["5.9.1", "Unknown"], wxCB_DROPDOWN);
    $self->{combo_box_2}->SetSelection(1);
    $self->{grid_sizer_1}->Add($self->{combo_box_2}, 0, wxALIGN_RIGHT, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    my $label_2 = Wx::StaticText->new($self->{notebook_2_pane_1}, wxID_ANY, "ADCIRC");
    $self->{grid_sizer_1}->Add($label_2, 0, wxALIGN_RIGHT, 0);
    
    $self->{combo_box_3} = Wx::ComboBox->new($self->{notebook_2_pane_1}, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, ["v56.0.2", "v55.02", "v55.01*", "v53.05"], wxCB_DROPDOWN);
    $self->{grid_sizer_1}->Add($self->{combo_box_3}, 0, wxALIGN_RIGHT, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{grid_sizer_1}->Add(0, 0, 0, 0, 0);
    
    $self->{button_1} = Wx::Button->new($self->{notebook_2_pane_1}, wxID_ANY, "Generate XDMF");
    $self->{button_1}->SetFont(Wx::Font->new(9, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, 0, ""));
    $self->{grid_sizer_1}->Add($self->{button_1}, 0, wxALIGN_RIGHT, 0);
    
    $self->{sizer_5}->Add(0, 0, 0, 0, 0);
    
    $self->{sizer_4} = Wx::BoxSizer->new(wxVERTICAL);
    $self->{sizer_3}->Add($self->{sizer_4}, 1, wxEXPAND, 0);
    
    $self->{sizer_4}->Add(0, 0, 0, 0, 0);
    
    $self->{sizer_4}->Add(0, 0, 0, 0, 0);
    
    $self->{sizer_4}->Add(0, 0, 0, 0, 0);
    
    $self->{sizer_4}->Add(0, 0, 0, 0, 0);
    
    $self->{notebook_2_XDMVTimeSeries} = Wx::Panel->new($self->{notebook_2}, wxID_ANY);
    $self->{notebook_2}->AddPage($self->{notebook_2_XDMVTimeSeries}, "XDMF Time Series");
    
    $self->{notebook_1_GridInput} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_GridInput}, "Grid and Input Utils");
    
    $self->{notebook_1_BuildTools} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_BuildTools}, "Build Tools");
    
    $self->{notebook_1_Performance} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_Performance}, "Performance");
    
    $self->{notebook_1_GridLibrary} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_GridLibrary}, "Grid Library");
    
    $self->{notebook_1_RunWizard} = Wx::Panel->new($self->{notebook_1}, wxID_ANY);
    $self->{notebook_1}->AddPage($self->{notebook_1_RunWizard}, "Run Wizard");
    
    $self->{notebook_2_pane_1}->SetSizer($self->{sizer_3});
    
    $self->{notebook_1_pane_1}->SetSizer($self->{sizer_2});
    
    $self->{panel_1}->SetSizer($self->{sizer_1});
    
    $self->Layout();
    # end wxGlade
    return $self;

}


# end of class MyFrame

1;

package MyApp;

use base qw(Wx::App);
use strict;

sub OnInit {
    my( $self ) = shift;

    Wx::InitAllImageHandlers();

    my $frame = MyFrame->new();

    $self->SetTopWindow($frame);
    $frame->Show(1);

    return 1;
}
# end of class MyApp

package main;

my $app = MyApp->new();
$app->MainLoop();
