; ------------------------------------------------------------
; Generated by wxPerl GUI Helper for Windows (Inno Setup tab)
; ------------------------------------------------------------

#define MyAppName "My Program"
#define MyAppExe "nhc-explorer.exe"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Your Name or Organization"

[Setup]

AppId={{867B9B5F-4631-A115-A18F-EF942C1A3877}}

AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}

DefaultDirName={localappdata}\Programs\{#MyAppName}
DefaultGroupName={#MyAppName}

PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline

UninstallDisplayIcon={app}\{#MyAppExe}

Compression=lzma2
SolidCompression=yes
WizardStyle=modern

OutputDir=..\release
OutputBaseFilename=nhc-explorer-setup
SetupIconFile=96x96.ico

[Files]

Source: "..\dist\nhc-explorer.exe"; DestDir: "{app}"; Flags: ignoreversion

[Tasks]

Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"

[Icons]

; Start Menu shortcut
Name: "{userprograms}\{#MyAppName}\{#MyAppName}"; Filename: "{app}\{#MyAppExe}"; IconFilename: "96x96.ico"

; Uninstall shortcut
Name: "{userprograms}\{#MyAppName}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"

; Optional desktop shortcut
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExe}"; Tasks: desktopicon; IconFilename: "96x96.ico"

[Run]

Filename: "{app}\{#MyAppExe}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent

[Code]

function InitializeSetup(): Boolean;
var
  ResultCode: Integer;
begin
  // Close running version during upgrade
  Exec(
    ExpandConstant('{cmd}'),
    '/C taskkill /IM "{#MyAppExe}" /T /F >NUL 2>NUL',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode
  );

  Result := True;
end;
